### ISSUE TITLE
InvalidException StandardModule

### ISSUE THREAD

**Issue by anthok** [sleuthkit/autopsy#1410]
Downloaded 3.1.3 and opened a case.

Then opened the same case back up 3.1.2, got this error.

    org.netbeans.InvalidException: StandardModule:org.sleuthkit.autopsy.core jarFile: C:\Program Files\Autopsy-3.1.2\autopsy\modules\org-sleuthkit-autopsy-core.jar: java.lang.UnsatisfiedLinkError: org.sleuthkit.datamodel.SleuthkitJNI.getVersionNat()Ljava/lang/String;

Now both versions won't open correctly.

**Comment by bcarrier** [comment]
Do you get the same error for both versions?  Did you have both versions of Autopsy open at the same time?

**Comment by anthok** [comment]
The error only popped up once, ever since both versions of autopsy no longer open correctly. The main window never shows and can no longer open existing autopsy case files. The loading screen pops up still but after the progress bar is complete, the program crashes.

You may be right about having both open at the same time (don't remember sorry), regardless I don't think it should corrupt both versions because of that.

**Comment by bcarrier** [comment]
When you say it "crashes" after the progress bar is complete, do you mean it goes away entirely or just that you get a blank screen and not the usual "splash screen" with the options to open and make cases? 

It's possible that during the initial message, you had the option to "Disable Modules" because of the loading error.  If you do that, you disable the core Autopsy module and you get behavior similar to what you are talking about.  

After the progress bar, if you have access to the menu items, go to "Tools -> Plugins". Choose the "Installed" tab.  You should see "Autopsy-Core", "Keyword Search", etc. Are they all listed as "Active"?  If not, try to Activate them again using that screen (button in the lower left).

**Comment by anthok** [comment]
The disable modules pop up showed, but I never clicked anything and exited the program. I guess by default it disabled them. When I was trying to open an existing .aut file and it would just go away entirely, no message or anything. I went in and activated and now it works. Thanks! 
Why aren't you able to have both version open at the same time? They use their own separate resources and exist independently.

**Comment by bcarrier** [comment]
Off the top of my head, there are a few issues with having multiple open:
1) As part of launching, it extracts some native libraries (dll files) to a temp folder.  That location is not currently Autopsy version-specific, so you get an error because it can't overwrite the one that is open by the version already running.  There is an easy fix for that though.
2) When Autopsy starts, it starts a local version of Solr. If there is one already there (because sometimes Solr doesn't shut down when Autopsy shutsdown), it kills it.  We'd need to spend some time changing that so that it is smarter about dealing with both situations of Solr not shutting down before (and therefore it should close the resources from the previous case) and Solr already existing because there is a 2nd case open.
3) Hashdatabases and keyword lists are in a version-generic location and we currently prevent the user from changing those lists while ingest is going on so that you can't add a hash value half-way in.  We would need to add more logic to keep the same behavior if another instance of Autopsy is using that database. 

It's not stuff that is impossible, just work that we haven't invested in to date.

I'll close this given that it seems to work now.  Thanks!
