### ISSUE TITLE
Huge negative Artifact ID shown in Autopsy 3.1.3

### ISSUE THREAD

**Issue by kefir-** [sleuthkit/autopsy#1601]
When analysing a case with Autopsy, all the artifacts under Results -> Extracted Content have Artifact IDs something like:

-9223372036854773113

I take it this is not intentional.

**Comment by esaunders** [comment]
This is intentional. We added support earlier this year for text extraction/indexing/searching of artifact content and we needed a way to distinguish keyword hits in files from keyword hits in artifacts. Rather than change the Solr schema we decided to split the range of object ids. Files have positive ids and artifacts have negative ids starting at Long.MIN_VALUE.

**Comment by kefir-** [comment]
OK, thanks for the feedback.
