### ISSUE TITLE
Email Parser results and keyword search issues

### ISSUE THREAD

**Issue by robertolarcher** [sleuthkit/autopsy#1698]
This is the scenario:
    1. new case
    2. source type: logical file
    3. file added: sample.pst
    4. run ingest module: Email Parser
    5. run ingest module: Keyword Search

The issues:
a) Searching for a keyword the body of the emails is not parsed and **no hits are reported**

![20151104 - 003](https://cloud.githubusercontent.com/assets/11318587/10941768/310b365c-830d-11e5-8c46-cc1cd4211426.PNG)

b) after selecting an email in Results>>E-Mail Message>>Default, the body of the email is displayed in the **results tab**

![20151104 - 001](https://cloud.githubusercontent.com/assets/11318587/10941540/2bc3adb0-830c-11e5-8a52-3c47b3cb60c5.PNG)

c) the **text tab** seems to contain the strings of all the sample.pst file (and not the text of the body of the selected message)

![20151104 - 002](https://cloud.githubusercontent.com/assets/11318587/10941562/4a72d092-830c-11e5-85fb-0e8b8ebaf14f.PNG)

**Comment by bcarrier** [comment]
4.0.0 does not currently index artifacts (the results of the ingest modules - and what is shown in Results).  The next release will likely fix this.  PST files can be compressed, so the text tab may show you the actual body text.  The "Text" tab could just be the "strings" of the file.  Is it the same as the "Strings" tab?

**Comment by mygitgradit1616** [comment]
Was functionality actually added to 4.1?  I've compiled 4.1 on my own, from the devel branch, but the keywordsearch module is still not returning text found from results of ingest modules, at least not that I can see.

**Comment by rcordovano** [comment]
Indexing of artifact text is in both the release-4.1.0 and develop branches. The calls to do so in the email parsing module are in ThunderbirdMboxFileIngestModule.addArtifact wihich is called from processPst and processMBox via processEmails; there is an additional direct call in processPst for encrypted email. We will verify that this is working and report back.

In the mean time, what sort of keyword search queries are you trying to do? I ask because a user was recently trying to do a query using a regex that included spaces. Such a regex will return no results because text searched using regular expressions is tokenized using the Solr white space tokenizer (literal searches are executed on another copy of the text tokenized with Solr standard tokenizer). For details, one nicely written reference is https://cwiki.apache.org/confluence/display/solr/Tokenizers. For Autopsy, the original design decision way back when keyword search was implemented was to store two copies of the text as processed by these two tokenizers, allowing for regex searches for things like U.S. phone numbers, email addresses, etc. in the white space tokenized copy - the standard tokenized copy splits up such things.

**Comment by mygitgradit1616** [comment]
I have a script that opens a binary file using a custom app and gets certain data from the file.  I post that data to the TSK_TEXT attribute in the TSK_EXTRACTED_TEXT artifact.  That works and I can see the file, along with the extracted text under Results, Extracted Content, Extracted Text.  But searching for the text produces no results.  So one of the results is the text "Made in America".  When I do a keyword search for America, it produces no results.  I've verified that search is working in general for text in text files and other common files.

Any help is appreciated.  Thanks

**Comment by BasisOlivers** [comment]
In order to index artifacts for keyword search, you need to call the method org.sleuthkit.autopsy.casemodule.services.Blackboard.indexArtifact(BlackboardArtifact artifact). Have you done this with the artifact that you created for the file?

Here is a sample on how to do this:

`Blackboard blackboard = Case.getCurrentCase().getServices().getBlackboard();
try {
	blackboard.indexArtifact(YOUR_ARTIFACT);
}
catch (BlackboardException ex) {
	YOUR EXCEPTION BEHAVIOR HERE.
}`

**Comment by mygitgradit1616** [comment]
That was it.  Many thanks!

**Comment by rcordovano** [comment]
Glad we could help. I am closing this issue.
