### ISSUE TITLE
Obsolete information in README.txt, Also README.txt should be markdown file.

### ISSUE THREAD

**Issue by ruchambapat** [sleuthkit/autopsy#2009]
The current README.txt contains Obsolete information , it should be updated and changed to markdown file.

**Comment by ruchambapat** [comment]
We have updated the file and changed it to markdown file. [Pull Request #2003](Obsolete information in README file is updated #2003)

**Comment by Chillli** [comment]
Pull request  #2003 has been generated for this problem. The old information about Autopsy 3 in README.txt was updated.
New file: https://github.com/delftswa2016/autopsy/blob/develop/README.md

**Comment by qilv1993** [comment]
I think more clear README.txt will enhance users experience

**Comment by rcordovano** [comment]
The README has been updated. Some, but not all, of the changes proposed in the pull request were accepted. 

After an initial change to a markdown file, the file has been made a text file again, The reason for this is that the README is distributed with the Windows installer. At this point it is deemed more important for a user running Windows to be able to easily open the README because it has an extension Windows recognizes as that of a text file.
