### ISSUE TITLE
HTML Content Viewer

### ISSUE THREAD

**Issue by bcarrier** [sleuthkit/autopsy#2223]
Make a new content viewer (lower right) that displays HTML files as HTML files (instead of just raw text).   Java provides panels that display HTML.

Extra work is needed for this kind of module to optionally reach out to external sites or load images that are in the same folder as the HTML file.

**Comment by tjmonson** [comment]
My friend and I are working on this feature. Currently, we are working on the isSupported function and want to make it so isSupported only returns true for files with the text/html mime type. We think this makes sense, because there is no reason to render a file unless it contains HTML. After a good deal of research, the best solution we've found is to use the Apache Tika library. The jar for this library is about 602kb in size. Since this is our first contribution to this project, we want to make sure it is okay for us to add this dependency. Also, if it is alright, should we update the README file with the dependency information?

**Comment by rcordovano** [comment]
Autopsy already uses Tika to determine the MIME type of files, as well as other mechanisms, as appropriate. This is the purpose of the file type identification ingest module. Your content viewer should determine whether or not there is an AbstractFile in the lookup of the Node that is passed to your implementation of isSupported. If you are only interested in files, it should ignore nodes that have artifacts in the lookup. 

Once you have an AbstractFile object in hand, you can query it using the getMIMEType method. If it is null, then the file type identification module has not been run. In that case, you may elect to do type detection using an instance of the FileTypeDetector class from the org.sleuthkit.autopsy.modules.filetypeid package in the Autopsy-Core NetBeans module.

**Comment by tjmonson** [comment]
Thank you so much for those pointers! We were able to implement what you suggested.

Unfortunately, we have run into another problem. The web view we are using will load resources that have valid URLs (such as images). It will also load local resources if the html file in question is a local file. However, the web view is not about to load resource files when the html file in question is loaded from a disk image (which is completely understandable). I'm wondering if it would be wise for us to create a temporary folder where we can store files from the disk image so the web view will have access to them locally. In my mind, this would require parsing the html file to find all the relevant src and href paths so we can determine which files to move into the temporary folder. Do you think doing this is worth the effort?

**Comment by rcordovano** [comment]
If you decide to do this, I would consider using a sub folder of the
modules output folder (Case.getModuleDirectory) instead of a sub folder of
a temp folder (Case.getTempDirectory). As a software engineer, rather than
an examiner/analyst, I am in no position to judge whether or not this would
be useful, sorry.

**Comment by bcarrier** [comment]
This was added sometime this past year.
