### ISSUE TITLE
DataResultViewer in 3rd party modules

### ISSUE THREAD

**Issue by LoWang123** [sleuthkit/autopsy#2290]
Hi,

I'm currently developing two new modules for autopsy 4. I thought it would be neat to include a DataResultViewer alongside my DataContentViewer. This would allow the user to easier identify interesting files from my ingest module.

Apparently the class AbstractDataResultViewer which I'm supposed to inherit is private within the package org.sleuthkit.autopsy.corecomponentinterfaces.

Am I missing something or is this a bug?

Best regards,
LoWang

**Comment by rcordovano** [comment]
Lo Wang, the documentation states that you need to extend  AbstractDataResultViewer which is indeed not visible.  However, the actual "extension point" is the public interface DataResultViewer, not AbstractDataResultViewer. AbstractDataResultViewer is intended to make development easier by supplying default implementations of many of the DataResultViewer methods, but it is not essential.  If you implement DataResultViewer, ensure that a no argument contructor is either implemented or generated for your viewer, and use the @ServiceProvider annotation to declare that your viewer is a DataResultViewer, it should be discovered at runtime and loaded as a tab in the data result viewers area.

**Comment by rcordovano** [comment]
Lo Wang, looking ahead, you may encounter another challenge with your viewer. The documentation assumes that  all DataResultViewers will have a NetBeans explorer view that displays the children of the node passed to them via DataResultViewer.setNode, and that the selected node in the explorer view will be passed on to the content viewers via the default DataContent that loads the content viewers into the tabs in the data content viewers area. This is the intended flow in Autopsy - the user selects a node in the tree view and the children of the node appear in the results viewers; then the user selects a node in a result viewer and the node is passed on to the content viewers. 

How exactly is a node from a result viewers explorer view passed on to the content viewers? The documentation says that "By default, when a node is selected, it is then passed to the default DataContent viewer (this is done in org.sleuthkit.autopsy.corecomponents.AbstractDataResultViewer)." This is no longer true. Instead, for the "core" viewers DataResultViewerTable and DataResultViewerThumbnail, the host DataResultPanel in the DataResultTopComponent provides an ExplorerManager for them to use in their explorer views. The DataResultPanel listens for selection property changes and passes the selected node on to the default DataContent. 

Your viewer cannot participate in this mechanism. It will need to assume responsibility for passing the selected node in its explorer view on to the content viewers. You will need to listen for the selection and do something like this:   

DataContent contentViewerTopComponent = Lookup.getDefault().lookup(DataContent.class);
contentViewerTopComponent.setNode(selectedNode); 

Alternatively, you can do what some other custom result viewer developers have done, which is to do something else in you result viewer besides displaying nodes for a user to select for viewing in a content viewer. Or you might decide that you want to implement a content viewer instead of, or in addition to, the result viewer. The documentation correctly states that content viewers to implement DataContentViewer and be service providers for that interface:

@ServiceProvider(service = DataContentViewer.class)

**Comment by rcordovano** [comment]
Ah, Lo Wang, reading your initial post again, I see you already have made a content viewer and an ingest module. Great! Hopefully you now know enough to proceed with the desired result viewer.

**Comment by rcordovano** [comment]
As a final note on this issue, AbstractDataResultViewer is now a public class
