### ISSUE TITLE
Python Autopsy Module - urllib error

### ISSUE THREAD

**Issue by robiame** [sleuthkit/autopsy#2303]
Hi,

I'm developing an ingest module in Python and I get an error only importing the urllib.
Find attached the log file showing the error.

Thanks

[autopsy_traces.log.0.txt](https://github.com/sleuthkit/autopsy/files/424544/autopsy_traces.log.0.txt)

**Comment by millmanorama** [comment]
I believe there was a bug that prevented python module loading many python libraries.  There is ( or will be shortly) a 4.1.1 release to fix this.

**Comment by rcordovano** [comment]
robiame, millmanorama is correct, you are experiencing a bug that is fixed in Autopsy 4.1.1, which should be publicly available shortly.  In the mean time, there is a relatively simple workaround.  Delete the following folder from your Autopsy 4.1.0 installation:
~Autopsy-4.1.0\autopsy\modules\ext\Lib
e.g., 
C:\Program Files\Autopsy-4.1.0\autopsy\modules\ext\Lib

**Comment by robiame** [comment]
Ok, thanks. It works with the workaround.
