### ISSUE TITLE
Linux - dialog does not close when loading existing case

### ISSUE THREAD

**Issue by marshalla99** [sleuthkit/autopsy#3330]
Another Linux "funny" in 4.5.1  - upon opening an existing case the "Image Writer Opening Case Resources" dialog box remains on screen after the case has loaded. The pop-up is titled, but blank. It can be closed manually.

Update - it's an inconsistent behaviour which seems to happen randomly.

**Comment by danpos** [comment]
@marshalla99 I confirm that weird and inconsistent behaviour in my tests.

**Comment by seannicholls** [comment]
I have also had this bug, on some builds the window refuses to close

**Comment by marshalla99** [comment]
Is it possible that this is related to the Timeline stalling ( #3247 ) and is indicative of a threading problem of some sort?

**Comment by rcordovano** [comment]
@marshalla99, a thread in a pool dedicated to case opening/closing operations actually dispatches tasks to the AWT event dispatch thread (EDT) to manage the display and dismissal of the progress dialogs while opening/closing case resources. The timeline tool is not one of those resources, so it is *probably* not a timeline-related problem, especially since the popup can be closed by clicking on it,  and all GUI code such as button click handling, etc. has to be executed in the EDT for Swing UI components. I suspect  therefore that the case opening operation completed somehow without dispatching a task to the EDT to dismiss the progress/status dialog. How that could happen is not immediately obvious to me, so my hypothesis may be just plain false. Some Autopsy log error messages or a thread dump via Oracle's VirtualVM when the problem occurs could help with diagnosis. Otherwise, we will have to just read the code and try to suss it out based on analyzing code paths, which can be difficult when multiple threads are involved.

**Comment by marshalla99** [comment]
That's helpful to know, thanks. This is a minor issue compared to the TimeLine, which is a real showstopper, but I'll see if I can get a log output or something to work with.

**Comment by marshalla99** [comment]
OK - Timeline is no longer a showstopper. I have it working in a CAINE 9.0 based environment. Not sure what the differences are between that and the Ubuntu live that I've been using, but the dialog not closing problem may also have been solved by the change in environment.

**Comment by marshalla99** [comment]
Ok - I think I have a fix for both Timeline and the non-closing dialog now. Those who are working on it, please could you check to see if you have libboost-dev installed?

**Comment by marshalla99** [comment]
Closing. absence of libboost-dev or libboost-devel (depending on distro.) now confirmed as the source of this problem.
