### ISSUE TITLE
Autopsy 4.8.0 Linux - Add data source "open logical files" issue

### ISSUE THREAD

**Issue by nannib** [sleuthkit/autopsy#4166]
Hi,
I installed Autopsy 4.8.0 in Ubuntu Mate 18.04, it works (even if, we have the same old issue #3562) but if I add data source: logical files
I get a Java lang Null Pointer exception and I cannot add anything more (image file, etc.) until I close the "add data source window" and I re-open it, then I can add ALL sources but the "logical file", that choice has got an issue...
In Autopsy 4.7.0 I did not get this problem....any ideas?
Thanks

**Comment by bcarrier** [comment]
Can you post the full stack trace?  You may need to click the "Details" button.

**Comment by nannib** [comment]
[full_stack_trace.txt](https://github.com/sleuthkit/autopsy/files/2429082/full_stack_trace.txt)

[messages.log](https://github.com/sleuthkit/autopsy/files/2429083/messages.log)

**Comment by dkarpo** [comment]
@nannib: Can you confirm if this is happening under Autopsy 4.9.0?  "Add Data Source -> Logical Files" seems to be working fine under Autopsy 4.9.0 on Debian testing and unstable so I'm wondering if this issue can be closed?

**Comment by nannib** [comment]
Just tried now, on my CAINE 10 (development) based on Ubuntu 18.04, and yes I've got the same issue :-(

**Comment by dkarpo** [comment]
Hello.  In some back and forth with Nanni I believe this issue is resolved and can be closed.  Nanni?  I tested Autopsy 4.8.0 on Caine directly and noted that the /etc/environment in Caine is setting a $_JAVA_OPTIONS environment variable which is altering some Java Swing parameters which is causing things like "Add Logical Files" in Autopsy to fail.  I've tested the solution as follows using the regular 'caine' user in Caine:

 Start a terminal emulator:
```bash
$ unset _JAVA_OPTIONS
$ sudo chmod 755 /usr/local/bin/autopsy
$ /usr/local/bin/autopsy
```

This will allow the regular 'caine' user to 'Add Logical Files' etc. however they won't be able to add a "Local Disk" since they don't have root permissions.  To allow Autopsy to run as 'root' on Caine the following solution works:

```bash
$ sudo /bin/su -
# rm -fr .autopsy
# unset _JAVA_OPTIONS
# chmod 755 /usr/local/bin/autopsy
# /usr/local/bin/autopsy
```

In the end the /etc/environment in Caine needs to be altered to remove the $_JAVA_OPTIONS environment variable and the /root/.autopsy folder needs to be removed as it is causing conflicts.  Once that is done it should all work fine.

**Comment by nannib** [comment]
yes, I confirm it works now!
