### ISSUE TITLE
Can't distinguish between multiple file exports

### ISSUE THREAD

**Issue by ctrlaltca** [sleuthkit/autopsy#5922]
Exporting files from a disk can take a lot of time.
Sometimes, eg. on friday evening, I run multiple file exports that can take the whole weekend to complete, so that on monday morning I can inspect the results of these exports.

The problem is that I can't distinguish between these multiple file exports:
 * while exporting I can see multiple jobs labeled only as "Extracting";
 * when a file export succeeds, a message box informs me that the export is complete, but without any additional info;
 * no entry is created in the case log/ingest messages viewer for the export.

Now back to my example, on monday morning I get back to the office and all the file export are complete but one. Since I'm unable to clearly identify the one that is still running, I can't start to work on the others.
Nowadays I'm trying to guess the running exports by looking at file dates and locke files on the filesystem, but it would be nicer to have this information available inside Autopsy.

**Comment by gdicristofaro** [comment]
Thanks for reaching out.  We are looking into doing the following to solve this problem:

- Have the progress indicator provide the name of the destination directory to which files are being exported so that you can differentiate between multiple progress indicators.
- Have the progress indicator show the file currently being exported in the progress text.

Would that meet your needs?

**Comment by ctrlaltca** [comment]
Thank you for the kind answer @gdicristofaro!
I think the first point is enough to fix the problem I initially reported.
The second point is probably a nice addition to fix the same problem when multiple exports of single files are using the same destination directory.

**Comment by gdicristofaro** [comment]
Sounds good.  We will try to address this soon.
